env:
  browser: true
  es6: true
  jquery: true
  commonjs: true

extends: 'eslint:recommended'

parserOptions:
  sourceType: module

globals:
  MT: true

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console:
    - off
